# Generated by Django 2.2.24 on 2021-10-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20211011_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
    ]
